// <auto-generated />
using System;
using CiberZone.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CiberZone.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CiberZone.API.Models.Pedido", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<string>("ArchivosJson").HasColumnType("text");
                b.Property<DateTime>("CreadoEn").HasColumnType("timestamp with time zone");
                b.Property<string>("Detalles").IsRequired().HasColumnType("text");
                b.Property<string>("Estado").IsRequired().HasDefaultValue("Pendiente")
                    .HasMaxLength(30).HasColumnType("character varying(30)");
                b.Property<string>("FechaPref").HasColumnType("text");
                b.Property<string>("Nombre").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("Origen").IsRequired().HasDefaultValue("Web")
                    .HasMaxLength(50).HasColumnType("character varying(50)");
                b.Property<string>("Servicio").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("Telefono").IsRequired().HasMaxLength(30).HasColumnType("character varying(30)");
                b.Property<int?>("UsuarioId").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("UsuarioId");
                b.ToTable("Pedidos");
            });

            modelBuilder.Entity("CiberZone.API.Models.Usuario", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<bool>("Activo").HasColumnType("boolean");
                b.Property<DateTime>("CreadoEn").HasColumnType("timestamp with time zone");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("text");
                b.Property<string>("Rol").IsRequired().HasDefaultValue("user")
                    .HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<string>("Username").IsRequired().HasMaxLength(100)
                    .HasColumnType("character varying(100)");
                b.HasKey("Id");
                b.HasIndex("Username").IsUnique();
                b.ToTable("Usuarios");
            });

            modelBuilder.Entity("CiberZone.API.Models.Pedido", b =>
            {
                b.HasOne("CiberZone.API.Models.Usuario", "Usuario")
                    .WithMany("Pedidos")
                    .HasForeignKey("UsuarioId")
                    .OnDelete(DeleteBehavior.SetNull);
                b.Navigation("Usuario");
            });

            modelBuilder.Entity("CiberZone.API.Models.Usuario", b =>
            {
                b.Navigation("Pedidos");
            });
#pragma warning restore 612, 618
        }
    }
}
